web/router.ex
defmodule Wedding.Router do
  use Wedding.Web, :router

  import Wedding.AuthPlug, only: [ensure_logged_in: 2]

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authed_area do
    plug :ensure_logged_in
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Wedding do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :logout

    scope "/users" do
      pipe_through :authed_area
      resources "/", UserController
    end

    scope "/tasks" do
      pipe_through :authed_area
      resources "/", TaskController
    end

    scope "/guests" do
      pipe_through :authed_area
      resources "/", GuestController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Wedding do
  #   pipe_through :api
  # end
end

web/models/user.ex
defmodule Wedding.User do
  use Wedding.Web, :model

  alias Wedding.Repo

  schema "users" do
    field :username, :string
    field :password, :string, virtual: true
    field :crypted_password, :string

    has_many :tasks, Wedding.Task
    has_many :guests, Wedding.Guest

    timestamps
  end

  @required_fields ~w(username password)
  @optional_fields ~w(crypted_password)

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
    |> unique_constraint(:username)
    |> validate_length(:username, min: 3)
    |> validate_length(:password, min: 5)
  end

  def login_changeset(model, params \\ :empty) do
    model
    |> cast(params, ~w(username password), ~w())
    |> unique_constraint(:username)
    |> validate_length(:username, min: 3)
    |> validate_length(:password, min: 5)
  end
  
  def stored_changeset(model, params \\ :empty) do
    model
    |> cast(params, ~w(id username crypted_password), ~w())
  end

  def with_guests do
    from u in Wedding.User,
    preload: [:guests]
  end

  def with_guests(user_id) do
    from u in with_guests,
    where: u.id == ^user_id
  end

  def guest_stats do
    from u in Wedding.User,
    inner_join: g in assoc(u, :guests),
    group_by: [g.coming, u.id],
    order_by: [g.coming, u.id],
    select: {u.id, u.username, count(g.id), g.coming}
  end

  def guest_stats(user_id) do
    from u in guest_stats,
    where: u.id == ^user_id
  end

  defp make_guest_stats([{uid, username, not_coming, false},
                         {uid, username, coming, true}]) do
    [id: uid, username: username, coming: coming, total: not_coming + coming]
  end

  defp make_guest_stats([{uid, username, not_coming, false}]) do
    [id: uid, username: username, coming: 0, total: not_coming]
  end

  defp make_guest_stats([{uid, username, coming, true}]) do
    [id: uid, username: username, coming: coming, total: coming]
  end

  def get_guest_stats do
    stats = Repo.all guest_stats
    stats |> Enum.map(&make_guest_stats/1)
  end

  def get_guest_stats(user_id) do
    stats = Repo.all guest_stats(user_id)
    make_guest_stats(stats)
  end

  def task_stats do
    from u in Wedding.User,
    inner_join: t in assoc(u, :tasks),
    group_by: [t.status, u.id],
    order_by: [t.status, u.id],
    select: {u.id, u.username, count(t.id), t.status}
  end

  def task_stats(user_id) do
    from u in task_stats,
    where: u.id == ^user_id
  end

  defp make_task_stats([{uid, username, not_done, false},
                        {uid, username, done, true}]) do
    [id: uid, username: username, done: done, total: done + not_done]
  end

  defp make_task_stats([{uid, username, not_done, false}]) do
    [id: uid, username: username, done: 0, total: not_done]
  end

  defp make_task_stats([{uid, username, done, true}]) do
    [id: uid, username: username, done: done, total: done]
  end

  def get_task_stats(user_id) do
    stats = Repo.all task_stats(user_id)
    make_task_stats(stats)
  end
end

web/controllers/user_controller.ex
defmodule Wedding.UserController do
  use Wedding.Web, :controller

  alias Wedding.User
  alias Comeonin.Bcrypt

  plug :scrub_params, "user" when action in [:create, :update]

  def user_by_id(id) do
    query = from u in User,
    preload: [:tasks],
    select: u
    Repo.get!(query, id)
  end

  def index(conn, _params) do
    users = Repo.all(User)
    current_user = get_session(conn, :logged_in)
    render(conn, "index.html", users: users, current_user: current_user)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)
    password_hash = Bcrypt.hashpwsalt(user_params["password"])
    user_data = Map.put(user_params, "crypted_password", password_hash)
    stored_changeset = User.stored_changeset(%User{}, user_data)

    if stored_changeset.valid? do
      case Repo.insert(stored_changeset) do
        {:ok, _user} ->
          conn
          |> put_flash(:info, "User created successfully.")
          |> redirect(to: user_path(conn, :index))
        {:error, changeset} ->
          render(conn, "new.html", changeset: changeset)
      end
    else
      render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = user_by_id(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Repo.get!(User, id)
    password_hash = Bcrypt.hashpwsalt(user_params["password"])
    user_data = Map.put(user_params, "crypted_password", password_hash)
    changeset = User.stored_changeset(user, user_data)

    if true do
      case Repo.update(changeset) do
        {:ok, user} ->
          conn
          |> put_flash(:info, "User updated successfully.")
          |> redirect(to: user_path(conn, :show, user))
        {:error, changeset} ->
          render(conn, "edit.html", user: user, changeset: changeset)
      end
    else
      render conn, "edit.html", user: user, changeset: changeset
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Repo.get!(User, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

web/views/user_view.ex
defmodule Wedding.UserView do
  use Wedding.Web, :view
end

web/templates/user/edit.html.eex
<h2>Edit user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :update, @user) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :username, "Username", class: "control-label" %>
    <%= text_input f, :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :password, "Password", class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<div>
  <span class="h3">Current user: </span>
  <span><%= @current_user %></span>
</div>
<div style="margin-top: 15px">
  <%= link "Log out", to: session_path(@conn, :logout), class: "btn btn-default btn-xs" %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Username</th>
      <th>Crypted password</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.crypted_password %></td>

      <td class="text-right">
        <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New user", to: user_path(@conn, :new) %>

web/templates/user/new.html.eex
<h2>New user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :create) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/show.html.eex
<h2>Show user</h2>

<ul>
  <li>
    <strong>Username:</strong>
    <%= @user.username %>
  </li>
</ul>

<h3>Tasks</h3>
<ul>
  <%= for t <- @user.tasks do %>
    <li>
      <%= link t.title,
      to: task_path(@conn, :show, t.id,
                    back_path: user_path(@conn, :show, @user.id)) %>
      (<%= if t.status do "Done" else "Not done" end %>)
    </li>
  <% end %>
</ul>

<%= link "Edit", to: user_path(@conn, :edit, @user) %>
<%= link "Back", to: user_path(@conn, :index) %>